image: docker:latest

stages:
  - build

before_script:
  - apk update && apk add git curl unzip grep sed coreutils npm
  - git config --global user.email "updater@umkus.com"
  - npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}

build:
  stage: build
  allow_failure: true
  script:
    - git clone https://Umkus:${BLOCKLIST_UPDATE_TOKEN}@github.com/Umkus/bad-ip-blocklist.git
    - cd bad-ip-blocklist
    - ./bin/build.sh
    - git status
    - git add dist/*.netset
    - git commit -m "Updated blocklists" || true
    - npm version patch || true
    - npm publish || true
    - git push || true
