version: '3.8'
services:
  node:
    build:
      dockerfile: node.Dockerfile
      context: .
    volumes:
      - .:/var/www

  nginx:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
