version: '3.8'
services:
  node:
    container_name: node
    image: ghcr.io/umkus/ipindex-node:latest
    restart: always

  nginx:
    container_name: nginx
    depends_on:
      - node
    image: ghcr.io/umkus/ipindex-nginx:latest
    ports:
      - 80:80
    restart: always
