Description: IP index service
AWSTemplateFormatVersion: 2010-09-09
Resources:
  PolicyLambda:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: Allow lambda write logs
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: "*"

  RoleLambda:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref PolicyLambda

  LambdaIpIndex:
    Type: AWS::Lambda::Function
    Properties:
      Code: ../dist/lambda/ip-index/
      Description: Fetches IP information
      Environment:
        Variables:
          NODE_ENV: production
      Handler: index.handler
      Layers:
        - !Sub arn:aws:lambda:eu-central-1:${AWS::AccountId}:layer:BetterSqlite3:1
      MemorySize: 128
      Role: !GetAtt RoleLambda.Arn
      Runtime: nodejs12.x
      Timeout: 5

  ConfigLambdaPermission:
    Type: AWS::Lambda::Permission
    DependsOn:
      - RestApi
      - LambdaIpIndex
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref LambdaIpIndex
      Principal: apigateway.amazonaws.com

  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: ip-index
      Description: Returns info about an IP

  RestApiLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

  RestApiAcct:
    Type: AWS::ApiGateway::Account
    Properties:
      CloudWatchRoleArn: !GetAtt RestApiLogsRole.Arn

  RestApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref RestApiDeployment
      RestApiId: !Ref RestApi
      StageName: v1

  RestApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ResourceIp
      - ResourceIpGet
    Properties:
      RestApiId: !Ref RestApi

  ResourceIp:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt RestApi.RootResourceId
      PathPart: '{ip}'
      RestApiId: !Ref RestApi

  ResourceIpGet:
    Type: AWS::ApiGateway::Method
    Properties:
      ApiKeyRequired: false
      HttpMethod: GET
      ResourceId: !Ref ResourceIp
      AuthorizationType: NONE
      Integration:
        ContentHandling: CONVERT_TO_TEXT
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Origin: "'*'"
            ResponseTemplates:
              application/json: ''
        PassthroughBehavior: WHEN_NO_MATCH
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaIpIndex.Arn}/invocations
      RestApiId: !Ref RestApi
      MethodResponses:
        - StatusCode: 200
          ResponseModels:
            application/json: Empty
          ResponseParameters:
            method.response.header.Access-Control-Allow-Origin: false

Outputs:
  ApiId:
    Value: !Ref RestApi
