name: Publish NPM package

on:
  push:
    paths:
      - 'dist/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm version patch --no-git-tag-version
      - uses: EndBug/add-and-commit@v4
        with:
          add: .
          message: 'Publishing new version'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
